#!/usr/bin/env python3

import json
from pathlib import Path
from typing import Any

from flask import Flask, render_template


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
REPORT_FILE = DATA_DIR / "nginx_report.json"

app = Flask(__name__)


def load_report() -> dict[str, Any]:
    """Load the JSON report generated by the nginx log analyzer."""
    if not REPORT_FILE.exists():
        return {
            "error": f"Report file not found: {REPORT_FILE}",
            "total_lines": 0,
            "categorized_lines": {},
            "top_source_ips": {},
            "top_paths": {},
            "top_suspicious_paths": {},
            "suspicious_keyword_hits": {},
            "request_anomalies": {},
            "ip_scores": {},
            "blocklist_candidates": {},
            "suspicious_lines": [],
            "unknown_path_examples": [],
        }

    with REPORT_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


def count_request_anomalies(report: dict[str, Any]) -> int:
    """Return total anomaly count from the anomaly dictionary."""
    anomalies = report.get("request_anomalies", {})
    return sum(anomalies.values()) if isinstance(anomalies, dict) else 0


@app.route("/")
def index():
    report = load_report()

    summary = {
        "total_lines": report.get("total_lines", 0),
        "suspicious_lines": len(report.get("suspicious_lines", [])),
        "anomalies": count_request_anomalies(report),
        "blocklist_candidates": len(report.get("blocklist_candidates", {})),
    }

    return render_template(
        "index.html",
        report=report,
        summary=summary,
    )


if __name__ == "__main__":
    app.run(debug=True)
