#!/usr/bin/env python3

import json
import os
import re
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any
from typing import Optional

from flask import Flask, render_template


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
REPORT_FILE = DATA_DIR / "nginx_report.json"

app = Flask(__name__)


def load_report() -> dict[str, Any]:
    """Load the JSON report generated by the nginx log analyzer."""
    if not REPORT_FILE.exists():
        return {
            "error": f"Report file not found: {REPORT_FILE}",
            "total_lines": 0,
            "categorized_lines": {},
            "top_source_ips": {},
            "top_paths": {},
            "top_suspicious_paths": {},
            "suspicious_keyword_hits": {},
            "request_anomalies": {},
            "ip_scores": {},
            "blocklist_candidates": {},
            "suspicious_lines": [],
            "unknown_path_examples": [],
        }

    with REPORT_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


def count_request_anomalies(report: dict[str, Any]) -> int:
    """Return total anomaly count from the anomaly dictionary."""
    anomalies = report.get("request_anomalies", {})
    return sum(anomalies.values()) if isinstance(anomalies, dict) else 0

def parse_nginx_timestamp(line: str) -> Optional[datetime]:
    """Parse timestamp from an Nginx access log line."""
    match = re.search(r"\[([^\]]+)\]", line)
    if not match:
        return None

    timestamp = match.group(1)

    try:
        return datetime.strptime(timestamp, "%d/%b/%Y:%H:%M:%S %z")
    except ValueError:
        return None


def extract_ip_from_log_line(line: str) -> str:
    """Extract source IP from the beginning of a log line."""
    parts = line.split()
    return parts[0] if parts else "unknown"


def build_last_seen_ips(report: dict[str, Any], limit: int = 10) -> list[dict[str, Any]]:
    """Build a list of recently seen IPs based on suspicious and unknown lines."""
    seen_ips: dict[str, dict[str, Any]] = {}

    candidate_lines = []

    for entry in report.get("suspicious_lines", []):
        line = entry.get("line")
        if line:
            candidate_lines.append(line)

    candidate_lines.extend(report.get("unknown_path_examples", []))

    for line in candidate_lines:
        timestamp = parse_nginx_timestamp(line)
        ip = extract_ip_from_log_line(line)

        if not timestamp:
            continue

        current = seen_ips.get(ip)

        if current is None or timestamp > current["timestamp"]:
            seen_ips[ip] = {
                "ip": ip,
                "timestamp": timestamp,
                "last_seen": timestamp.strftime("%Y-%m-%d %H:%M:%S %z"),
                "line": line,
            }

    return sorted(
        seen_ips.values(),
        key=lambda item: item["timestamp"],
        reverse=True,
    )[:limit]

def build_last_7_days_overview(report: dict[str, Any]) -> dict[str, Any]:
    """Build a recent activity overview based on the newest timestamp in the report."""
    candidate_entries = []

    for entry in report.get("suspicious_lines", []):
        line = entry.get("line")
        if line:
            candidate_entries.append({
                "type": "suspicious",
                "line": line,
                "ip": entry.get("ip", extract_ip_from_log_line(line)),
            })

    for line in report.get("unknown_path_examples", []):
        candidate_entries.append({
            "type": "anomaly",
            "line": line,
            "ip": extract_ip_from_log_line(line),
        })

    parsed_entries = []

    for entry in candidate_entries:
        timestamp = parse_nginx_timestamp(entry["line"])
        if not timestamp:
            continue

        parsed_entries.append({
            **entry,
            "timestamp": timestamp,
            "last_seen": timestamp.strftime("%Y-%m-%d %H:%M:%S %z"),
        })

    if not parsed_entries:
        return {
            "recent_ip_count": 0,
            "suspicious_count": 0,
            "anomaly_count": 0,
            "latest_timestamp": None,
            "entries": [],
        }

    latest_timestamp = max(entry["timestamp"] for entry in parsed_entries)
    cutoff = latest_timestamp - timedelta(days=7)

    recent_entries = [
        entry for entry in parsed_entries
        if entry["timestamp"] >= cutoff
    ]

    recent_ips = {entry["ip"] for entry in recent_entries}

    return {
        "recent_ip_count": len(recent_ips),
        "suspicious_count": sum(1 for entry in recent_entries if entry["type"] == "suspicious"),
        "anomaly_count": sum(1 for entry in recent_entries if entry["type"] == "anomaly"),
        "latest_timestamp": latest_timestamp.strftime("%Y-%m-%d %H:%M:%S %z"),
        "entries": sorted(
            recent_entries,
            key=lambda item: item["timestamp"],
            reverse=True,
        )[:15],
    }


def sort_dict_by_value_desc(data: dict[str, Any]) -> list[tuple[str, Any]]:
    """Sort a flat dictionary by value descending."""
    if not isinstance(data, dict):
        return []
    return sorted(data.items(), key=lambda item: item[1], reverse=True)


def sort_ip_scores(data: dict[str, dict[str, Any]]) -> list[tuple[str, dict[str, Any]]]:
    """Sort IP scores by score desc, suspicious_hits desc, requests desc."""
    if not isinstance(data, dict):
        return []

    return sorted(
        data.items(),
        key=lambda item: (
            item[1].get("score", 0),
            item[1].get("suspicious_hits", 0),
            item[1].get("requests", 0),
        ),
        reverse=True,
    )


def sort_blocklist_candidates(
    data: dict[str, dict[str, Any]]
) -> list[tuple[str, dict[str, Any]]]:
    """Sort blocklist candidates by score desc, suspicious_hits desc, requests desc."""
    if not isinstance(data, dict):
        return []

    return sorted(
        data.items(),
        key=lambda item: (
            item[1].get("score", 0),
            item[1].get("suspicious_hits", 0),
            item[1].get("requests", 0),
        ),
        reverse=True,
    )


@app.route("/")
def index():
    report = load_report()

    summary = {
        "total_lines": report.get("total_lines", 0),
        "suspicious_lines": len(report.get("suspicious_lines", [])),
        "anomalies": count_request_anomalies(report),
        "blocklist_candidates": len(report.get("blocklist_candidates", {})),
    }

    sorted_report = {
        "error": report.get("error"),
        "total_lines": report.get("total_lines", 0),
        "categorized_lines": sort_dict_by_value_desc(report.get("categorized_lines", {})),
        "top_source_ips": sort_dict_by_value_desc(report.get("top_source_ips", {})),
        "top_paths": sort_dict_by_value_desc(report.get("top_paths", {})),
        "top_suspicious_paths": sort_dict_by_value_desc(report.get("top_suspicious_paths", {})),
        "suspicious_keyword_hits": sort_dict_by_value_desc(report.get("suspicious_keyword_hits", {})),
        "request_anomalies": sort_dict_by_value_desc(report.get("request_anomalies", {})),
        "ip_scores": sort_ip_scores(report.get("ip_scores", {})),
        "blocklist_candidates": sort_blocklist_candidates(report.get("blocklist_candidates", {})),
        "unknown_path_examples": report.get("unknown_path_examples", []),
    }

    recent_suspicious = report.get("suspicious_lines", [])[-10:]
    recent_unknown = report.get("unknown_path_examples", [])[-10:]
    last_seen_ips = build_last_seen_ips(report)
    last_7_days = build_last_7_days_overview(report)
    
    return render_template(
        "index.html",
        report=sorted_report,
        summary=summary,
        recent_suspicious=recent_suspicious,
        recent_unknown=recent_unknown,
        last_seen_ips=last_seen_ips,
        last_7_days=last_7_days,
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5002))
    host = os.environ.get("HOST", "0.0.0.0")
    app.run(debug=True, host=host, port=port)
