#!/usr/bin/env python3

import json
import os
from pathlib import Path
from typing import Any

from flask import Flask, render_template


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
REPORT_FILE = DATA_DIR / "nginx_report.json"

app = Flask(__name__)


def load_report() -> dict[str, Any]:
    """Load the JSON report generated by the nginx log analyzer."""
    if not REPORT_FILE.exists():
        return {
            "error": f"Report file not found: {REPORT_FILE}",
            "total_lines": 0,
            "categorized_lines": {},
            "top_source_ips": {},
            "top_paths": {},
            "top_suspicious_paths": {},
            "suspicious_keyword_hits": {},
            "request_anomalies": {},
            "ip_scores": {},
            "blocklist_candidates": {},
            "suspicious_lines": [],
            "unknown_path_examples": [],
        }

    with REPORT_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


def count_request_anomalies(report: dict[str, Any]) -> int:
    """Return total anomaly count from the anomaly dictionary."""
    anomalies = report.get("request_anomalies", {})
    return sum(anomalies.values()) if isinstance(anomalies, dict) else 0


def sort_dict_by_value_desc(data: dict[str, Any]) -> list[tuple[str, Any]]:
    """Sort a flat dictionary by value descending."""
    if not isinstance(data, dict):
        return []
    return sorted(data.items(), key=lambda item: item[1], reverse=True)


def sort_ip_scores(data: dict[str, dict[str, Any]]) -> list[tuple[str, dict[str, Any]]]:
    """Sort IP scores by score desc, suspicious_hits desc, requests desc."""
    if not isinstance(data, dict):
        return []

    return sorted(
        data.items(),
        key=lambda item: (
            item[1].get("score", 0),
            item[1].get("suspicious_hits", 0),
            item[1].get("requests", 0),
        ),
        reverse=True,
    )


def sort_blocklist_candidates(
    data: dict[str, dict[str, Any]]
) -> list[tuple[str, dict[str, Any]]]:
    """Sort blocklist candidates by score desc, suspicious_hits desc, requests desc."""
    if not isinstance(data, dict):
        return []

    return sorted(
        data.items(),
        key=lambda item: (
            item[1].get("score", 0),
            item[1].get("suspicious_hits", 0),
            item[1].get("requests", 0),
        ),
        reverse=True,
    )


@app.route("/")
def index():
    report = load_report()

    summary = {
        "total_lines": report.get("total_lines", 0),
        "suspicious_lines": len(report.get("suspicious_lines", [])),
        "anomalies": count_request_anomalies(report),
        "blocklist_candidates": len(report.get("blocklist_candidates", {})),
    }

    sorted_report = {
        "error": report.get("error"),
        "total_lines": report.get("total_lines", 0),
        "categorized_lines": sort_dict_by_value_desc(report.get("categorized_lines", {})),
        "top_source_ips": sort_dict_by_value_desc(report.get("top_source_ips", {})),
        "top_paths": sort_dict_by_value_desc(report.get("top_paths", {})),
        "top_suspicious_paths": sort_dict_by_value_desc(report.get("top_suspicious_paths", {})),
        "suspicious_keyword_hits": sort_dict_by_value_desc(report.get("suspicious_keyword_hits", {})),
        "request_anomalies": sort_dict_by_value_desc(report.get("request_anomalies", {})),
        "ip_scores": sort_ip_scores(report.get("ip_scores", {})),
        "blocklist_candidates": sort_blocklist_candidates(report.get("blocklist_candidates", {})),
        "unknown_path_examples": report.get("unknown_path_examples", []),
    }

recent_suspicious = report.get("suspicious_lines", [])[-10:]
recent_unknown = report.get("unknown_path_examples", [])[-10:]
    
return render_template(
    "index.html",
    report=sorted_report,
    summary=summary,
    recent_suspicious=recent_suspicious,
    recent_unknown=recent_unknown,
)


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5002))
    host = os.environ.get("HOST", "0.0.0.0")
    app.run(debug=True, host=host, port=port)
